### ISSUE TITLE
Add support for VMWare

### ISSUE THREAD

**Issue by matthewvalimaki** [flix-tech/vagrant-kubernetes#8]
As I've hit a VBox bug I'd like to give this a try on VMWare. Unless someone else can provide necessary changes I can give it a try myself. For VM specific changes I looked at `Makefile` and `vg-01-repartition.sh`, is that all? Also in `Makefile` there's `.vagrant/repartinioned` which does something with disks. Could explanation for what the purpose of it all is be added? :)

**Comment by hanikesn** [comment]
So this part is there because the default disk size for the Vagrant Debian Box is 8GB which is much too small for our use-case. If you're happy with a smaller disk size you can basically remove those steps.

* `vg-01-repartition.sh` resizes the disk inside the box
* https://github.com/flix-tech/vagrant-kubernetes/blob/v1.7.1/Makefile#L19 is the main part that's Virtualbox specific and basically does an offline resize of the vdi

I think it wouldn't be too much of a hassle to add support for VMWare, but at this point it might actually make sense to migrate the provisioning to packer. Also I have some ideas for a 2.0 which would allow dynamically setting the ip range at the start of the box.

**Comment by matthewvalimaki** [comment]
Closing this as I did not have time to work on the feature and updated used container images to resolve my issue.
